18F/cv_faq

- Dockerfile
- docker-compose.yml
> Add basic docker configuration.

- _content/animals/can-i-walk-my-dog.md
- _content/animals/since-tigers-can-get-infected-should-i-worry-about-my-pet-cat.md
- _content/animals/what-animals-can-get-covid-19.md
- _content/animals/what-should-i-do-if-my-pet-gets-sick.md
- _content/animals/why-are-animals-being-tested-when-people-cant.md
- _content/basics/what-is-a-novel-coronavirus.md
- _content/keeping-home-safe/if-someone-in-my-house-gets-sick.md
- _content/protect-yourself/should-i-go-to-work-if-there-is-an-outbreak-in-my-community.md
- _content/protect-yourself/what-should-people-at-higher-risk-of-serious-illness-with-covid-19-do.md
Fixes #501 
- Adds 5 new FAQs to `animals` category
- Adds one missing question about going to work
- Minor edits and link additions
> Adds 6 new FAQs: CDC animals, work

- _content/symptoms-and-testing/if-i-recover-from-covid19-will-i-be-immune.md
- _content/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19.md
- _content/symptoms-and-testing/what-is-serology-testing.md
Fixes issue #516 
Adds questions about testing methods and immunity. These questions are not duplicate to the FDA content about testing. 
See [PREVIEW LINK](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-content-4-16/symptoms-and-testing/)
> Adds 3 new CDC FAQs for Symptoms & Testing

- _content/financial-help/how-can-i-check-the-status-of-my-economic-impact-payment.md
Fixes #524 
- Adds Treasury FAQ related to payment app
> Adds 1 new Treasury FAQ

- _content/protect-yourself/can-cdc-tell-me-when-it-is-safe-to-go-back.md
Fixes #527 
[PREVIEW](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-4-17/protect-yourself/can-cdc-tell-me-when-it-is-safe-to-go-back/)
- Adds new CDC FAQ: "Can CDC tell me or my employer when it is safe for me to go back to work/school after recovering from or being exposed to COVID-19?"
> Adds 1 new CDC FAQ 

- _content/symptoms-and-testing/what-is-serology-testing.md
- Minor edit to serology testing QA derived from tracker
> Minor edit to CDC FAQ from tracker

- _content/medications/prescribe-chloroquine-or-hydroxychloroquine-off-label.md
Fixes #533 
Added "May health care providers prescribe chloroquine phosphate or hydroxychloroquine sulfate off-label to treat patients with COVID-19?" to "Medication" category
Added "What are the most important things I need to know to keep myself and others safe when I go to the grocery store during the pandemic?" to "How to protect yourself" category
[PREVIEW LINK](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fda-content-4-20/)
> Adds 2 new FDA FAQs

- _data/homepage_order.yml
- `medications` is missing from the homepage sort data file; adds missing category to file
> Adds missing category to homepage data file

- _content/rumors/are-uscis-offices-closed-for-covid.md
- _content/travel/when-will-the-borders-reopen.md
Fixes #543
[PREVIEW](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/dhs-4-21/)
- Edits two existing DHS FAQs
> Edits two existing DHS FAQs

- README.md
Adds transition updates per handoff conversation yesterday.
> add netlify and localization readme updates

- _content/symptoms-and-testing/are-there-home-tests.md
- _content/symptoms-and-testing/if-antibody-tests-not-used-for-diagnosis.md
- _content/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19.md
- _content/symptoms-and-testing/when-will-other-tests-be-authorized.md
Fixes #542
- Are there any tests that I can purchase to test myself at home for COVID-19? [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fda-4-22/symptoms-and-testing/are-there-home-tests/)
- What is the difference between the types of tests available for SARS-CoV-2? (combined with What kind of test is being used to diagnose if I have COVID-19?) [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fda-4-22/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19/)
- If antibody tests are not used for diagnosis or exclusion of SARS-CoV-2 infection, what is their purpose? [Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fda-4-22/symptoms-and-testing/if-antibody-tests- …
> Edits and adds FDA FAQs (2 new)

- _content/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19.md
Fixes #570 
- Revise 1 CDC FAQ "What kind of test is being used to diagnose if I have COVID-19?" to  reflect changes sent by agency content lead
- Deletes change made/ merged from PR #564 (where content from FDA FAQ "What is the difference between the types of tests available for SARS-CoV-2?" picked up by site tracker was combined with this existing questions)
> Revise 1 CDC FAQ for Symptoms & Testing

- _content/protect-yourself/am-i-at-risk-for-covid-19-from-packages-or-products-shipping-from-china.md
Fixes #582 
Update includes revised question wording and answer
See [preview link](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-4-24/protect-yourself/)
> Update 1 CDC FAQ about mail & packages

- _content/animals/can-bats-in-us-get-covid19-and-spread-it-to-people.md
- _content/animals/can-wild-animals-spread-covid19-to-people-and-pets.md
- _content/animals/since-tigers-can-get-infected-should-i-worry-about-my-pet-cat.md
Issue #575 
Added new questions: wild animals and bats, revised question about cats.
[Preview link](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-animal-4-24/animals/)
> Added two animal Qs, edited 1

- _content/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19.md
- Edits answer to _What kind of test is being used to diagnose if I have COVID-19?_
> Edits testing FAQ with CDC approval

- _content/financial-help/what-do-i-do-if-i-cant-pay-mortgage.md
- Fixes typo and adds descriptive link text for accessibility (✅ both approved by agency partner)
> Fix typo and add descriptive link

- _content/symptoms-and-testing/what-are-the-symptoms-and-complications-that-covid-19-can-cause.md
Fixes #601 
- Updates answer to add new symptoms
- Changes url to match Symptoms page on CDC website (at the request of agency content lead)
- Updates the date
> Updated to add new symptoms, revise url and date

- _content/water-transmission/can-the-covid-19-virus-spread-through-drinking-water.md
- _content/water-transmission/can-the-covid-19-virus-spread-through-pools-and-hot-tubs.md
- _content/water-transmission/is-the-covid-19-virus-found-in-feces.md
- _content/water-transmission/should-wasterwater-workers-take-extra-precautions-to-protect-from-covid19.md
- Edits water transmission FAQs with CDC approval
- Fixes typo with CDC approval
> Edits CDC water transmission FAQs

- _content/symptoms-and-testing/what-are-the-symptoms-and-complications-that-covid-19-can-cause.md
- Updates CDC symptoms FAQ
> **What are the symptoms and complications that COVID-19 can cause?**
> Current symptoms reported for patients with COVID-19 have included mild to severe respiratory illness with fever1, cough, shortness of breath or difficulty breathing, chills, repeated shaking with chills, muscle pain, headache, sore throat, and new loss of taste or smell. Read about COVID-19 Symptoms.
> 1. Fever may be subjective or confirmed
Changed to:
> **What are the symptoms and complications that COVID-19 can cause?** 
> People with COVID-19 have had a wide range of symptoms reported – ranging from mild symptoms to severe illness. People with these symptoms or combinations of symptoms may have COVID-19:
> - Cough
> - Shortness of breath or difficulty breathing
> Or at least two of …
> Updates CDC symptoms FAQ (agency approved)

- _assets/css/_header.scss
- _assets/css/_hero.scss
- _assets/css/_home.scss
- _assets/css/_overrides.scss
- _assets/css/_uswds_theme.scss
- _assets/js/search.js
- _includes/meta.html
* Adds Open Sans 800 weight font per #629 
* Bold all matching search terms in local search dropdown per #625
> Open Sans extra-bold added

- _agencies/doj.md
- _content/rumors/did-fema-seize-supplies-from-va.md
- _content/rumors/is-fema-deploying-the-military.md
- _content/rumors/is-fema-seizing-personal-protective-equipment.md
- _content/rumors/is-fema-suspending-rent-for-people-in-certain-states.md
Fixes #641
- Is FEMA suspending rent for people in certain states?
- Did FEMA seize supplies from The Department of Veterans Affairs (VA)?
- Is FEMA seizing medical supplies?
- Is FEMA deploying the military?
> Adds/updates FEMA content

- _content/financial-help/what-do-i-do-if-a-payment-was-sent-to-someone-who-died.md
- Address line breaks were not preserved in our previous merge. For example:
> For Georgia, Iowa, Kansas, Kentucky, Virginia: Atlanta Refund Inquiry Unit 4800 Buford Hwy Mail Stop 112 Chamblee, GA 30341
- This PR corrects the line breaks for readability:
> **For Georgia, Iowa, Kansas, Kentucky, Virginia:**
> 
> Atlanta Refund Inquiry Unit
> 4800 Buford Hwy
> Mail Stop 112
> Chamblee, GA 30341
> Adds line breaks to Treasury update

- _content/animals/if-my-pet-had-species-specific-coronavirus-are-they-more-likely-to-get-covid-19.md
> Update to species-specific coronavirus question in animals category

- 404.html
NOTE: Due to Federalist caching, the preview link doesn't include this update at the moment. You can test locally.
> Update 404 title text, as requested by Analytics Logic

- _content/rumors/are-uscis-offices-closed-for-covid.md
Update date for re-opening to the public of USCIS offices from May 3 to June 4.
[Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/2020-05-12-DHS-USCIS-Date-Update/rumors/are-uscis-offices-closed-for-covid/)
> Update re-opening date on USCIS

- _content/rumors/are-uscis-offices-closed-for-covid.md
Promote *content | design* changes.
* Content
* `preview-content` (approved content) <- *Content branch*
* `master` (production) <- `preview-content`
* Design/development
* `preview` (approved design) <- *Feature branch*
* *Content admin* for merge to `preview-content` (approved content)
* *Project lead* for merge to `preview` (approved design / behavior changes)
> Preview content to production

- _content/travel/when-will-the-borders-reopen.md
_Promote changes._
* Content
* `preview-content` (approved content) <- *Content branch*
* `master` (production) <- `preview-content`
* Design/development
* `preview` (approved design) <- *Feature branch*
* *Content admin* for merge to `preview-content` (approved content)
* *Project lead* for merge to `preview` (approved design / behavior changes)
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/20200519-DHS-edits/travel/when-will-the-borders-reopen/)
> Updated DHS border reopening FAQ

- _content/travel/when-will-the-borders-reopen.md
_Promote changes._
* Content
* `preview-content` (approved content) <- *Content branch*
* `master` (production) <- `preview-content`
* Design/development
* `preview` (approved design) <- *Feature branch*
* *Content admin* for merge to `preview-content` (approved content)
* *Project lead* for merge to `preview` (approved design / behavior changes)
> Merging corrected DHS border reopening date

- Gemfile
- Gemfile.lock
- package-lock.json
- package.json
This should close out all the Synk dependency PRs, with the exception of USWDS. There will likely be consequences of that update, so leaving it as-is.
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/dep-upgrade/)
> Dependency upgrades

- _content/financial-help/i-am-a-veteran-do-i-need-to-provide-information-to-irs.md
- _content/support-for-business/how-to-apply-for-a-small-business-loan.md
- _content/support-for-business/how-to-apply-for-benefits.md
_Minor updates to three Treasury FAQs_
😎 **Preview Links**
* [I am a veteran and I receive Compensation and Pension (C&P) benefits. Do I need to provide information to the IRS to receive my payment?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Treasury-updates-2020-05-21/financial-help/i-am-a-veteran-do-i-need-to-provide-information-to-irs/)
* [How do I apply for a small business loan?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Treasury-updates-2020-05-21/support-for-business/how-to-apply-for-a-small-business-loan/)
* [How do I apply for small business or self-employment benefits?](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Treasury-updates-2020-05-21/support-for-business/how-t …
> Updates to existing Treasury FAQs

- _content/protect-yourself/how-do-i-prepare-for-hurricane-season-during-covid19.md
- _content/protect-yourself/if-i-need-to-evacuate-my-home-during-the-covid19-pandemic.md
* Content
:sunglasses: 
- [PREVIEW How do I prepare...](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FEMA-hurricane-season-FAQs-2020-05-22/protect-yourself/how-do-i-prepare-for-hurricane-season-during-covid19/)
- [PREVIEW If I need to evacuate...](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FEMA-hurricane-season-FAQs-2020-05-22/protect-yourself/if-i-need-to-evacuate-my-home-during-the …
> FEMA hurricane season FAQs

- _content/parents-and-children/what-is-multisystem-inflammatory-syndrome-in-children.md
_Added new FAQ from CDC site on MIS-C_
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-MIS-C-new-FAQ-2020-05-26/parents-and-children/what-is-multisystem-inflammatory-syndrome-in-children/)
> Created new CDC MIS-C FAQ

- _content/travel/which-airports-have-enhanced-travel-screening.md
- _content/travel/which-countries-are-subject-travel-restrictions-us.md
_1. Changed airports providing enhanced screening from 13 to 15 and added the two new airports. 2. Added Brazil to the list of countries with travel restrictions._
* Content
:sunglasses: 
[Airports](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/DHS-airport-screening-2020-05-27/travel/which-airports-have-enhanced-travel-screening/)
[Restricted Travel](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/DHS-airport-screening-2020-05-27/travel/which-countries-are-subject-t …
> DHS airport screening 2020 05 27

- _categories/financial-help.md
- _content/financial-help/how-will-the-irs-know-where-to-send.md
- _content/financial-help/i-have-not-filed-my-tax-return-for-2018-or-2019.md
_Initial testing of two redirects from deleted pages to the category landing page (redirects on the category financial-help.md file), and two redirects from old page names to updated page names._
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/redirecting-deprecated-content-2020-06-03/)
> Redirecting deprecated content

- _categories/funerals.md
- _categories/keeping-home-safe.md
- _categories/parents-and-children.md
- _categories/protect-yourself.md
- _categories/rumors.md
- _categories/spread.md
- _categories/travel.md
- _content/parents-and-children/while-school-is-out-how-can-i-help-my-child-continue-learning.md
- _content/parents-and-children/while-school-is-out-should-i-limit-time-with-older-adults.md
- _content/protect-yourself/why-cloth-face-coverings-instead-of-facemasks.md
- _content/rumors/are-older-folks-the-only-ones-at-risk.md
- _content/rumors/is-fema-deploying-the-military.md
- _content/rumors/is-the-government-sending-everyone-money.md
- _content/rumors/is-there-a-national-lockdown.md
- _content/rumors/should-i-stock-up-on-food-and-supplies.md
- _content/symptoms-and-testing/what-is-antibody-testing.md
- _content/travel/should-I-cancel-my-international-travel.md
- _content/travel/which-countries-are-subject-travel-restrictions-us.md
_Redirects from deletions and moves that have accumulated over time and are contributing to poor site search experience_
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/more-deprecated-urls-2020-06-03/)
> FAQ redirects - balance of categories and pages

- _categories/funerals.md
- _content/funerals/are-department-of-veterans-affairs-national-cemeteries-open.md
_VA cemeteries => Funerals category redirect was incorrectly redirected to category landing page, now points to correct specific FAQ_
* Content
> Corrects misdirected cemeteries redirect

- _categories/travel.md
- index.html
_Pointing deprecated pages to site root when no suitable redirect available_
- retirement community deprecated content
- airline industry content
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/redirects-to-site-root-2020-06-05/)
> Pointing deprecated pages to site root when no suitable redirect available

- _content/funerals/can-i-schedule-burial-national-cemetery.md
- _content/funerals/can-i-schedule-committal-service-military-funeral-service-honors.md
- _content/water-transmission/can-the-covid-19-virus-spread-through-sewerage-systems.md
- _content/water-transmission/should-wasterwater-workers-take-extra-precautions-to-protect-from-covid19.md
New copy for existing FAQs for two CDC water-related FAQs and two VA burial-related FAQs.
* Content
:sunglasses: 
[Schedule a Burial](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-water-and-va-burials-2020-06-11/funerals/can-i-schedule-burial-national-cemetery/)
[Commital Service](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/cdc-water-and-va-burials-2020-06-11/funerals/can-i-schedul …
> CDC (Water) and VA (Burial) Changes

- _content/financial-help/if-my-financial-situation-changed-could-i-be-eligible-for-snap.md
- _content/financial-help/what-happens-to-snap-recipients-who-cannot-meet-work-requirements-due-to-covid19.md
- _content/food-safety/are-meats-compromised-by-covid19.md
- _content/food-safety/is-there-guidance-on-food-planning.md
- _content/food-safety/where-can-i-find-info-about-nutrition-assistance.md
- _content/parents-and-children/can-parents-pick-up-meals-for-their-kids-without-them-present.md
- _content/parents-and-children/can-schools-provide-home-delivery-of-meals.md
- _content/parents-and-children/can-schools-provide-multiple-meals-at-once.md
- _content/parents-and-children/can-schools-serve-meals-while-they-are-closed.md
- _content/parents-and-children/do-school-meals-still-have-to-meet-nutrition-requirements.md
- _content/parents-and-children/what-action-is-being-taken-to-ensure-children-have-food-while-schools-are-closed.md
- _content/protect-yourself/can-the-public-still-visit-national-forest-recreation-sites.md
_Change 12 USDA posts to reflected the updated date of June 11, 2020, following Audra's review and approval._
* Content
:sunglasses: 
[Eligible for Snap](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-date-changes-2020-06-12/financial-help/if-my-financial-situation-changed-could-i-be-eligible-for-snap/)
[Snap Recipients](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/usda-date-changes-2020-06-12/financial-help/what-happens-to-snap-recipients-who-cannot-meet-wor …
> USDA Date Changes

- _content/financial-help/can-snap-participants-order-groceries-online.md
- _content/financial-help/if-my-financial-situation-changed-could-i-be-eligible-for-snap.md
- _content/financial-help/what-happens-to-snap-recipients-who-cannot-meet-work-requirements-due-to-covid19.md
- _content/food-safety/are-meats-compromised-by-covid19.md
- _content/food-safety/is-there-guidance-on-food-planning.md
- _content/food-safety/where-can-i-find-info-about-nutrition-assistance.md
- _content/parents-and-children/can-parents-pick-up-meals-for-their-kids-without-them-present.md
- _content/parents-and-children/can-schools-provide-home-delivery-of-meals.md
- _content/parents-and-children/can-schools-provide-multiple-meals-at-once.md
- _content/parents-and-children/can-schools-serve-meals-while-they-are-closed.md
- _content/parents-and-children/do-school-meals-still-have-to-meet-nutrition-requirements.md
- _content/parents-and-children/what-action-is-being-taken-to-ensure-children-have-food-while-schools-are-closed.md
- _content/protect-yourself/can-the-public-still-visit-national-forest-recreation-sites.md
Change 12 USDA posts to reflected the updated date of June 11, 2020, following Audra's review and approval.
* Content
:sunglasses:
[Eligible for Snap](https://demo-er2epz2vb.18f.gov/financial-help/if-my-financial-situation-changed-could-i-be-eligible-for-snap/)
[Snap Recipients](https://demo-er2epz2vb.18f.gov/financial-help/what-happens-to-snap-recipients-who-cannot-meet-work-requirements-due-to-covid19/)
[Meat Products](https://demo-er2epz2vb.18f.gov/food-safety/are-meats-compromised-by-covid19/)
[Nutrition …
> USDA date updates

- _content/medications/should-I-take-acquarium-chloroquine-phosphate.md
_Create new FAQ, delete old FAQ, and add redirect to change the question regarding human consumption of acquarium chloquine phosphate._
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FDA-aquarium-hydroxychlorine-20200616/medications/should-i-take-acquarium-chloroquine-phosphate/)
> Aquarium chloroquine phosphate

- _content/basics/why-is-the-disease-called-covid-19.md
- _content/parents-and-children/are-children-at-risk.md
- _content/parents-and-children/are-symptoms-of-COVID-19-different-in-children.md
- _content/parents-and-children/how-can-i-protect-my-child-from-COVID-19.md
- _content/parents-and-children/how-do-i-prepare-my-child-for-an-outbreak.md
- _content/parents-and-children/should-children-wear-face-masks.md
- _content/parents-and-children/what-is-multisystem-inflammatory-syndrome-in-children.md
- _content/protect-yourself/does-cdc-recommend-facemasks.md
- _content/protect-yourself/how-can-I-help-protect-myself.md
- _content/protect-yourself/if-i-need-to-evacuate-my-home-during-the-covid19-pandemic.md
- _content/protect-yourself/is-it-safe-to-get-medical-care-for-other-conditions.md
- _content/protect-yourself/what-should-i-do-if-i-had-close-contact-with-someone-who-has-covid-19.md
- _content/rumors/is-there-a-national-lockdown.md
- _content/rumors/on-medicare-and-someone-offered-me-a-test.md
- _content/spread/can-the-virus-that-causes-covid-19-be-spread-through-food.md
- _content/spread/how-does-the-virus-spread.md
- _content/spread/what-is-community-spread.md
- _content/symptoms-and-testing/should-i-be-tested-for-covid-19.md
Added three new CDC FAQs (prepare children for community outbreak, recommend facemasks, doctors appointments) and updated 12 CDC FAQs. Also corrected the date on 3 FEMA FAQs.
_https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/groups-at-higher-risk.html_
* Content
:sunglasses: 
[Why Called Covid](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-updates-and-additions/basics/why-is-the-disease-called-covid-19/)
[Prepare Children for …
> CDC Updates and Additions (and minor FEMA date changes)

- _content/financial-help/what-do-I-do-if-I-lost-my-EPP-debit-card.md
- _content/financial-help/who-is-eligible-for-payment.md
- _content/financial-help/why-am-i-receiving-a-debit-card.md
- _content/food-safety/is-there-guidance-on-food-planning.md
Two new Treasury FAQs (what is I lost my EPP card; why am I receiving a debit card), and one update (EPP eligibility).
_Two new Treasury FAQs (what is I lost my EPP card; why am I receiving a debit card), and one update (EPP eligibility)._
* Content
:sunglasses: 
[EIP Eligibility](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/treasury-EPP-eligibility/financial-help/who-is-eligible-for-payment/)
[Lost EIP Debit Card](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/tr …
> Treasury Additions and Updates

- _content/medications/are-there-any-vaccines-to-prevent-covid-19.md
_Added FDA "Are there any vaccines..." to Medications category_
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FDA-update-vaccines-06-24/medications/are-there-any-vaccines-to-prevent-covid-19/)
> Added FDA "Are there any vaccines..." to Medications category

- _content/medications/are-there-any-vaccines-to-prevent-covid-19.md
_Google Search Console indicated older, deleted content on this topic that was still indexed, so it's being redirected to the new FAQ, specifically /rumors/are-there-any-vaccines/ and /medications/are-there-any-vaccines_
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/redirects-to-new-FDA-page-06-24/)
> Redirects from bad urls to new FDA FAQ

- _content/basics/what-treatments-are-available.md
_Removed old redirect from deleted page and pointed it to new, more authoritative answer, specifically /medications/are-there-any-vaccines/ had been pointed to /basics/what-treatments-are-available/ and is now pointed to /medications/are-there-any-vaccines-for-covid-19_
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/redirects-to-new-FDA-page-06-24/)
> Removed old redirect from deleted page and repointed it

- _data/homepage_promotion.yml
> Fix broken internal link

- _data/homepage_promotion.yml
Removed word "have" to fix line wrapping on protect yourself box
* Content
> Removed word "have" to fix line wrapping

- _content/parents-and-children/how-can-i-keep-my-children-healthy.md
_Changed Redirect-from to Redirect_from so /parents-and-children/while-school-is-out-how-can-i-keep-my-family-healthy/ will successfully redirect to /parents-and-children/how-can-i-keep-my-children-healthy
_
* Content
:sunglasses: [While School is Out](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Redirect-Fix-20200701//parents-and-children/while-school-is-out-how-can-i-keep-my-family-healthy/)
> CDC-Redirect Fix

- _categories/parents-and-children.md
- _categories/rumors.md
- index.html
Implement redirect froms for
/k12-childcare/
/retirement-communities/
/roumors/
* Content
:sunglasses: 
[/k12-childcare/](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fix-404s-20200710/parents-and-children/)
[/retirement-communities/](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fix-404s-20200710/)
[/roumors/](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv …
> Address inbound pages resulting in 404s

- _layouts/agency.html
Fixes #916 
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/fix-agencies/agency/cdc/)
> Fix agency list

- _content/pregnancy/can-covid-19-be-passed-from-a-pregnant-woman-to-her-fetus-or-newborn.md
- _content/pregnancy/how-can-pregnant-women-protect-themselves-from-getting-covid-19.md
- _content/pregnancy/what-is-the-risk-to-pregnant-women-of-getting-covid-19.md
- _content/pregnancy/what-should-breastfeeding-mothers-do.md
Made revisions to four CDC pregnancy FAQs.
_Made revisions to four CDC pregnancy FAQs._
* Content
:sunglasses: 
[Passed During Pregnancy](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Pregnancy-2020-07-23/pregnancy/can-covid-19-be-passed-from-a-pregnant-woman-to-her-fetus-or-newborn/)
[Pregnant Women Protect Themselves](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Pregnancy-2020-07-23/pregnancy/how-can-pregnant-women-protect-themselves-from-getting-covid- …
> CDC Pregnancy FAQs

- _categories/pregnancy.md
- _categories/underlying-conditions.md
Added i-am-pregnant-what-are-the-risks.md to underlying-conditions category and placed in position three. Moved to position one on pregnancy category
* Content
:sunglasses: 
- [PREVIEW URL - Landing](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/update-content-for-production-category-test/)
- [PREVIEW URL - Underlying Conditions](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/update-content-for-production-category-test/underlying-conditions/#i-am-pregnant-and-worri …
> Multi-category and promoted content test

- Gemfile
> Revert "Rollback category changes"

- _content/financial-help/do-online-classes-still-qualify-for-gi-bill-benefits.md
- _content/funerals/are-department-of-veterans-affairs-national-cemeteries-open.md
- _content/funerals/can-i-schedule-committal-service-military-funeral-service-honors.md
- _content/protect-yourself/can-i-visit-patient-at-department-of-veterans-affairs-facility.md
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/va-updates-jd-2020-08-12/)
[GI bill](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/va-updates-jd-2020-08-12/do-online-classes-still-qualify-for-gi-bill-benefits/)
[VA cemeteries open](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/va-updates-jd-2020-08-12/are-department-of-veterans-affairs-national-cemeteries-open/)
[Can I schedule …
> Minor updates to VA content

- _categories/financial-help.md
- _categories/medications.md
- _categories/rumors.md
- _content/financial-help/help-for-people-who-have-federal-student-loans.md
- _content/rumors/contact-tracer-asked-for-confidential-information.md
- _content/rumors/should-i-trust-ads-for-products-to-prevent-treat-cure-covid-19.md
- _content/support-for-business/calls-to-small-businesses-promising-quick-financial-relief.md
Add new FTC FAQs and place on Category listing pages
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/ftc-additions-2020-08-12-jd/)
- [CARES Act student loans - financial help](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/ftc-additions-2020-08-12-jd/help-for-people-who-have-federal-student-loans/)
- [Should I trust ads - rumors, meds](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/ftc-additions-2020-08-12-jd/should-i-trust-ads-for-products-to-prev …
> Add new FTC FAQs and place on Category listing pages

- package-lock.json
- package.json
- styles/_uswds_theme.scss
- styles/index.scss
Implements #893
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/uswds-2.8/)
> Upgrade to USWDS 2.8

- _content/financial-help/missed-tax-day.md
- _content/protect-yourself/what-do-i-do-if-exposed-to-covid-19.md
2 to _content\financial-help\missed-tax-day.md
1 to _content\protect-yourself\what-do-i-do-if-exposed-to-covid-19.md
* Content
:sunglasses Check on preview
Old URL: [/protect-yourself/what-should-i-do-if-i-had-close-contact-with-someone-who-has-covid-19/]()
Goes to: [/what-do-i-do-if-exposed-to-covid-19/]()
Old URL: [/financial-help/what-if-i-cant-complete-my-taxes-by-april-15/]()
Old URL: [/financial-help/i-have-not-filed-my-tax-return-for-2018-or-2019/]()
Goes to: [/missed-tax-day/]()
> add 3 redirects

- _content/travel/when-will-the-borders-reopen.md
Changed dates and source
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/2020-08-18-dhs-update/when-will-the-borders-reopen/)
> Update DHS content when-will-the-borders-reopen.md

- _categories/rumors.md
- _content/rumors/hazard-pay.md
_Addition of FEMA Hazard pay to Rumors_
* Content
:sunglasses: [Hazard Pay](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FEMA.Hazard-Pay.082620/hazard-pay/)
> FEMA Hazard Pay

- _categories/symptoms-and-testing.md
- _content/symptoms-and-testing/close-contact-will-i-be-tested.md
New CDC FAQ on contact tracing
* Content
> New CDC FAQ (contact tracing) and addition to symptoms and testing category page

- _categories/basics.md
- _content/basics/covid-19-guidance-in-multiple-languages.md
- _content/symptoms-and-testing/should-i-be-tested-for-covid-19.md
_Updated "Should I be tested..." and added "guidance in multiple languages."_
* Content
:sunglasses: 
[Should I Be Tested](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-FDA-Symptoms-Multilingual/should-i-be-tested-for-covid-19/)
[Multiple Languages](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-FDA-Symptoms-Multilingual/covid-19-guidance-in-multiple-languages/)
> CDC-FDA Update and Addition

- _categories/animals.md
- _categories/financial-help.md
- _categories/parents-and-children.md
- _categories/protect-yourself.md
- _content/animals/avoid-animal-adoption-scam.md
- _content/financial-help/manage-bills-during-covid-19.md
- _content/financial-help/nursing-home-take-stimulus-check.md
- _content/parents-and-children/remote-learning-childrens-privacy.md
- _content/protect-yourself/avoid-contact-tracing-scam.md
_Added five new FAQs from the FTC, on animal adoption scams, managing bills, nursing homes taking stimulus checks, remote learning and children's privacy, and avoiding contact tracing scams. 
Ignoring test-jest fail, since it is known problem and spurious._
* Content
:sunglasses: 
[Animal Adoption Scam](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FTC-New-FAQs-091020/avoid-animal-adoption-scam/)
[Nursing Home](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FTC-New-F …
> FTC New FAQs

- _content/animals/avoid-animal-adoption-scam.md
> Fix extra non-breaking spaces

- _categories/financial-help.md
- _content/financial-help/unemployment-help.md
- _content/symptoms-and-testing/should-i-be-tested-for-covid-19.md
_FEMA addition (help for unemployed). CDC date change (testing)._
* Content
:sunglasses: 
[Unemployment Help](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FEMA-CDC-Updates/unemployment-help/)
[Tested](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FEMA-CDC-Updates/should-i-be-tested-for-covid-19/)
> FEMA Addition and CDC Date Change

- _categories/financial-help.md
- _categories/support-for-business.md
- _content/financial-help/will-government-provide-second-round-economic-impact-payments.md
- _content/support-for-business/paycheck-protection-loan-forgiveness.md
Adding FAQ on 2nd round of EIPs to Financial Help, and PPP loan forgiveness to Support for Business.
~Need to~ confirm citation w/liaison for 2nd round FAQ [Confirmed 09/26/20]
* Content
:sunglasses:
- [PPP loan forgiveness](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/2020-09-25-Treasury-FAQs/support-for-business/#how-do-i-get-my-paycheck-protection-program-loan-forgiven)
- [2nd round EIPs](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/2020-09-25-Treasury-FAQs/fin …
> Adding two Treasury FAQs

- _content/financial-help/do-online-classes-still-qualify-for-gi-bill-benefits.md
_Updated the "Will I still qualify for my GI Bill benefits?"_
* Content
:sunglasses: 
[PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/VA-GI-Bill-Benefits-09292020/do-online-classes-still-qualify-for-gi-bill-benefits/)
> VA-GI-Bill-Ed-Assistance

- _content/protect-yourself/can-i-visit-patient-at-department-of-veterans-affairs-facility.md
_Updated VA FAQ with new guidance._
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/VA-Visits-09292020/can-i-visit-patient-at-department-of-veterans-affairs-facility/)
> Updated VA FAQ

- _categories/caring-for-children.md
- _categories/school-meals.md
- _content/caring-for-children/considerations-for-returning-child-to-school.md
- _content/disinfecting-sanitizing/if-someone-in-my-house-gets-sick.md
- _content/protect-yourself/how-can-i-prepare-for-covid19-at-work.md
> Redirect fixes

- _content/food-drug-safety/are-food-products-a-risk-for-spread.md
- _content/food-drug-safety/is-the-food-supply-safe.md
- _content/food-drug-safety/will-there-be-food-shortages.md
- _content/older-people-special-precautions/who-is-at-higher-risk-for-serious-illness-from-covid-19.md
- _content/support-for-business/what-capital-assistance-is-available-to-small-business-owners.md
Added re-directs for seach console errors
* Content
> Added re-directs for seach console errors

- _content/spread-transmission/can-the-covid-19-virus-spread-through-pools-and-hot-tubs.md
Remove parens redirect
* Content
> Update to remove parens redirect

- _categories/activities-events-gatherings.md
- _content/activities-events-gatherings/holidays.md
- _content/spread-transmission/how-does-the-virus-spread.md
_Added CDC holidays/Halloween FAQ and updated "How is the virus spread" to include airborne transmission_
* Content
:sunglasses: 
[Holidays](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Halloween-10062020/holidays/)
[Spread](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Halloween-10062020/how-does-the-virus-spread/)
> CDC Holidays

- _content/activities-events-gatherings/holidays.md
_Updated date for Halloween FAQ._
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Halloween-date-10082020/holidays/)
> Changed date

- _content/protect-yourself/how-do-i-prepare-for-hurricane-season-during-covid19.md
- _content/symptoms-and-testing/kind-of-test-used-to-diagnose-covid19.md
- _content/travel/what-is-the-risk-of-getting-covid-19-on-an-airplane.md
_Updates to hurricanes; risk of airplanes; and types of tests to diagnose COVID._
* Content
:sunglasses: 
[Airplane](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Updates-10092020/what-is-the-risk-of-getting-covid-19-on-an-airplane/)
[Kind of Test](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Updates-10092020/kind-of-test-used-to-diagnose-covid19/)
[Hurricanes](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Updates-1009 …
> CDC Updates

- _categories/caring-for-children.md
- _categories/disinfecting-sanitizing.md
- _categories/spread-transmission.md
- _content/disinfecting-sanitizing/cleaning-disinfecting-car-seats-booster-seats.md
Adding CDC car seat disinfection question
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/2020-10-15-cdc/disinfecting-sanitizing/#do-car-seats-and-booster-seats-need-extra-cleaning-and-disinfection-to-prevent-spread-of-covid-19)
> Adding CDC car seat disinfection question

- package-lock.json
- package.json
> Dependancy upgrades

- _categories/older-people-special-precautions.md
- _categories/protect-yourself.md
- _categories/symptoms-and-testing.md
- _content/older-people-special-precautions/seasonal-allergies-increased-risk.md
- _content/protect-yourself/mask-provide-seasonal-allergy-protection.md
- _content/protect-yourself/protect-myself-seasonal-allergies.md
- _content/symptoms-and-testing/covid-19-seasonal-allergies.md
_Four new CDC FAQs on seasonal allergies, symptom overlap with COVID and implications for masks, etc._
* Content
:sunglasses: 
[Seasonal Allergies](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Seasonal-Allergies-2020-10-30/protect-myself-seasonal-allergies/)
[Seasonal Allergies Increased Risk](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Seasonal-Allergies-2020-10-30/seasonal-allergies-increased-risk/)
[Mask Protect from Seasonal …
> CDC Seasonal Allergies

- _categories/cleaning-disinfecting-sanitizing.md
- _categories/underlying-conditions.md
- _data/homepage_order.yml
- _data/homepage_promotion.yml
_1. Renamed Older people & those who need special precautions to Underlying Conditions. 2. Renamed Disinfecting and sanitizing to Cleaning, disinfecting, and sanitizing. Created appropriate redirects._
* Content
:sunglasses: 
[Cleaning, disinfecting, and sanitizing](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Category-Changes-Minor-20201105/cleaning-disinfecting-sanitizing/)
[Test Disinfecting Redirect](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Category-Change …
> Minor category renaming

- scripts/components/search-results.js
- scripts/services/search/click-tracking.js
- scripts/services/search/constants.js
- scripts/services/search/index.js
> Click tracking now with less calories and commits

- scripts/components/click-tracking.js
- scripts/components/index.js
- scripts/components/search-results.js
- scripts/services/search/click-tracking.js
- scripts/services/search/constants.js
> Alternate click tracking strategy

- _content/holidays.md
Updated CDC holidays FAQ to mention Thanksgiving, specifically.
test-htmlproofer fail is spurious and tested in production.
* Content
:sunglasses:
[Holidays](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Thanksgiving-Holidays-2020-11-20/holidays/)
> Updated CDC Holidays FAQ

- Rakefile
- package.json
> Disable external link checking with CI infra

- _categories/treatments-vaccines-immunity.md
- _content/covid-19-vaccine.md
- _data/homepage_promotion.yml
_Added new FAQ (covid-19-vaccine) and associated link in Treatments, Vaccines category. Also replaced the "will I be immune" question in the grey box on the homepage with this FAQ._
* Content
> FDA Vaccine FAQ--New

- _content/covid-19-vaccine.md
- _content/what-treatments-are-available.md
1. Added sentence directing users to CDC info on vaccines to "What treatments are available for COVID-19?" 2. Moved four redirects from "What treatments are available...? to "Are there any vaccines or other medical products to prevent COVID-19?"
* Content
> Two FDA Updates

- scripts/components/search-results.js
- scripts/services/search/local.js
> Fallback to local search when search.gov returns a failure

- _content/vaccine-development.md
_Updated vaccine development FAQ to include a note regarding the EUA for the Pfizer-BioNTech vaccine._
* Content
:sunglasses: 
[Vaccine Development](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-20201217/vaccine-development/)
> Updated vaccine-development

- _content/vaccine-development.md
Added EUA link to vaccine dev FAQ
* Content
:sunglasses: [How many vaccines...](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FDA-eua-link-2020-12-17/treatments-vaccines-immunity/#how-many-covid-19-vaccines-are-under-development)
> Add EUA link to vaccine dev FAQ

- _content/air-travel.md
_Repaired source URL for How should I prepare for air travel during the pandemic?_
* Content
:sunglasses: 
[Air Travel](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-URL-Fix-20201217/air-travel/)
> Updated FAQ with bad source url

- _content/air-travel.md
- _content/vaccine-development.md
Update bad source url on Air Travel FAQ
* Content
:sunglasses: [Air Travel](https://demo-er2epz2vb.18f.gov/air-travel/)
> Update source bad source url on Air Travel FAQ

- _content/covid-19-vaccine.md
- _content/vaccine-development.md
Updates to two vaccine FAQs to reflect Moderna EUA
* Content
* [] Assign an appropriate reviewer:
:sunglasses: 
* [How many vaccines...](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FDA-eua-moderna-2012-12-18/treatments-vaccines-immunity/#how-many-covid-19-vaccines-are-under-development)
* [Are there any vaccines...](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/FDA-eua-moderna-2012-12-18/treatments-vaccines-immunity/)
> FDA FAQs - EUA Moderna

- _content/air-travel.md
- _content/covid-19-vaccine.md
- _content/vaccine-development.md
- package-lock.json
- package.json
Updates to two vaccine-related FAQs to include Moderna vaccine approval. Update to USWDS 2.10.
* Content
:sunglasses: 
* [Are there any...](https://faq.coronavirus.gov/treatments-vaccines-immunity/#are-there-any-vaccines-or-other-medical-products-to-prevent-covid-19)
* [How many...](https://faq.coronavirus.gov/treatments-vaccines-immunity/#how-many-covid-19-vaccines-are-under-development)
> Update to vaccine FAQs and bump USWDS to 2.10

- _content/vaccine-development.md
_Updated the vaccine development FAQ to reflect that the Moderna vaccine is currently being administered in the U.S._
* Content
:sunglasses: 
[Vaccine Development](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Vaccine-Update-20201224/vaccine-development/)
> Update Moderna vaccine info

- _content/will-government-provide-second-round-economic-impact-payments.md
Updated info on second round of EIPs
* Content
:sunglasses: [2nd Round EIPs](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/treasury-2nd-round-eip-2020-12-29/financial-help/#will-the-government-provide-a-second-round-of-direct-payments-checks-to-people)
> Update to Treasury's 2nd round of EIPs FAQ

- _categories/treatments-immunity.md
- _categories/vaccines.md
- _content/why-might-someone-create-stigma.md
- _data/homepage_order.yml
- _data/homepage_promotion.yml
Changes to homepage, including
* Reordering of Top Questions
* Rename Treatments, vaccines, and immunity to Treatments and immunity.
* Add category Vaccines
* Reword description under Economic support 
* Content
:sunglasses: 
[Home page](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Homepage-Changes-20210106/)
> 2021-01-06 Homepage changes 

- _categories/treatments-immunity.md
Remove duplicate /basics redirect
* Content
:sunglasses: [/basics to /covid-19-facts ](https://faq.coronavirus.gov/basics/)
> Update treatments-immunity category redirects

- package-lock.json
- package.json
- webpack.config.js
> Swap uglify for terser

- package-lock.json
- package.json
- webpack.config.js
> Dependency Deploy 2020-01-11 

- styles/_footer.scss
* Content
Before:
After:
After after:
> Footer disclaimer left alignment

- _agencies/irs.md
- _content/employee-retention-credit.md
- _content/how-to-apply-for-a-small-business-loan.md
- _content/how-to-apply-for-benefits.md
- _content/paycheck-protection-loan-forgiveness.md
- _content/small-medium-businesses-paid-leave.md
- _content/what-do-i-do-if-i-cant-pay-rent.md
_Updated to three Treasury/IRS FAQ, three SBA FAQs, and one agency name (IRS)._
* Content
:sunglasses: 
[Apply for Benefits](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Treasury-SBA-Updates-2021-02-03/how-to-apply-for-benefits/)
[Small Business Loan](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/Treasury-SBA-Updates-2021-02-03/how-to-apply-for-a-small-business-loan/)
[PPP Loan Forgiveness](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/c …
> Treasury/IRS and SBA Updates

- _categories/protect-yourself.md
- _categories/vaccines.md
- _content/bad-vaccine-reaction.md
- _content/get-vaccine.md
- _content/how-does-the-virus-spread.md
- _content/immunity-vaccine.md
- _content/number-vaccine-shots.md
- _content/stop-mask-after-vaccine.md
_Five new and one updated CDC FAQ_
* Content
:sunglasses: 
Update
[Spread](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-2021-02-03/how-does-the-virus-spread/)
New
[Number of Shots](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-2021-02-03/number-vaccine-shots/)
[Bad Reaction](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-2021-02-03/bad-vaccine-reaction/)
[Get Vaccine](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app. …
> CDC: New and Updated FAQs

- package-lock.json
- package.json
> Dependencies - 20200208

- package-lock.json
- package.json
> Dependencies -  20200211

- package-lock.json
- package.json
> Dependencies - 20200212

- package-lock.json
- package.json
> Dependencies - 20200215

- package-lock.json
- package.json
> Dependencies - 20210219

- _content/how-can-i-protect-myself.md
_Minor change to How can I protect myself?    _
* Content
:sunglasses: 
[Protect Myself](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/CDC-Minor-Change-2021-02-23/how-can-i-protect-myself/)
> Minor content change

- _content/how-can-i-protect-myself.md
- package-lock.json
- package.json
* Content
:sunglasses:  [Protect yourself content edit](https://faq.coronavirus.gov/protect-yourself/)
> Dependencies, USWDS 2.10.1 update, and minor content edit

- _content/how-can-i-protect-myself.md
- package-lock.json
- package.json
> Dependencies - 20210223
