18F/cv_faq

jest-puppeteer.config.js, package-lock.json, package.json
Fixes #464 by moving away from `http-server` in favor of `serve` while running tests.
=> Use serve over http-server due to security vulnerabilities. 

.circleci/config.yml
If HTMLProofer fails, we still want to see the results of jest. 
This is especially poignant if we temporarily have a broken link — we want to make sure we’re not introducing further issues, which could sneak in and hide behind the broken link failure. 
The configuration in this PR results in running the tests commands in parallel, and will report both their statuses (as well as the build status — if the site could be built) to GitHub:
=> Always run both test commands in CI.

_categories/travel.md
- Replaces travel advisory alert banner to match CDC
- Wording isn't ideal; perhaps we can request edits
=> Replaces travel advisory alert banner

_content/pregnancy/what-should-breastfeeding-mothers-do.md
- Adds link to translated version
_It seems to me the relevant text ("recommendations for proper pump cleaning") should be translated inline. The current link text implies users will read the preceding English text to understand where the link goes._
=> Adds link to translated pregnancy FAQ

_categories/medications.md
The `homepage_order` front matter is no longer needed for category sorting. These have been removed from all other categories, this one was added after the initial PR however.
=> Remove homepage_order from medication

_content/financial-help/what-happens-to-snap-recipients-who-cannot-meet-work-requirements-due-to-covid19.md, _content/parents-and-children/what-action-is-being-taken-to-ensure-children-have-food-while-schools-are-closed.md, _content/protect-yourself/can-the-public-still-visit-national-forest-recreation-sites.md
There are 4 USDA FAQs where we recommended the following revisions:
- Combine two FAQs (Will National Forest recreation sites and facilities stay open?) and (What can the public do to practice social distancing while recreating on National Forest System lands?) into a single FAQ - [**"Can the public still visit National Forest recreation sites and facilities? If so, how can they do safely?"**](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/edits-usda-4-27/protect-yourself/can-the-public-still-visit-national-forest-recreation-sites/)
- Remove url link to a PDF for state agency directors, not the general public for one FAQ: [**What happens to SNAP recipients who can’t meet the work requirements due to the coronavirus …
=> Adds edited USDA FAQs

.github/ISSUE_TEMPLATE/content-template.md, .github/ISSUE_TEMPLATE/engineering-issue-template.md
Added issue templates for content and engineering. Both include a definition of done checklist, and the engineering issue template includes other details including acceptance criteria and other tasks. 
Resolves #550
=> Update issue templates

_includes/scripts.html
Remove DAP code, due to GTM usage superseding it. #218 
[Preview](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/remove-dap/)
=> Remove DAP snippet

api/openapi.yaml, api/v1/questions.json
This updates the input for question `sources`, as changed in #523. Thank you @brentryanjohnson for catching my oversight.
Docs:
https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/update-json-sources-schema/api/
Endpoints:
https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/update-json-sources-schema/api/v1/categories.json
https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/update-json-sources-schema/api/v1/questions.json
=> Update source list to be consistent with changes

.github/PULL_REQUEST_TEMPLATE.md
I think we've confused matters too much by introducing separate staging branches for dev and content purposes, so let's make all our lives easier by going back to a single one.
=> Simply workflow by going back to one staging branch

_assets/js/app.js, _includes/accordion.html, _layouts/category.html, test/categories.html.test.js
Implements #744
On category pages:
* Use single-select accordions
* Update the current URL to include the question hash on click.
Note that the URL is updated without updating browser history.
This will support:
* bookmarking/sharing use cases
* allow analytic reports to track clicks via the URL change events, pending Google Tag Manager configuration by our analytics partners
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/category-chapters/)
=> Category chapters

Gemfile, Gemfile.lock, _config.yml, _content/medications/are-there-any-vaccines.md
We have some old cached content from previously-named versions of some pages that still show . See #729
This PR adds the `jekyll-redirect-from` plugin, which adds the ability to do a client-side redirect via Javascript. Federalist does not support actual 301/302 redirects - see https://github.com/18F/federalist/issues/755 This plugin sets `<meta name="robots" content="noindex">` which should prevent search.gov from indexing the redirect files.
This branch adds a single redirect - [https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/add-redirects/rumors/are-there-any-vaccines/](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/add-redirects/rumors/are-there-any-vaccines/)
* Content …
=> Add redirect support

Rakefile, _content/support-for-business/where-should-a-small-business-go-to-find-help.md
Due to Twitter rate-limiting (http 429) all requests from our CircleCI jobs, skip Twitter URLs on the HTML proofer tests. #831 
* Content
=> HTML proofer - skip Twitter URLs

Gemfile.lock, scripts/services/search/constants.js
This is a hotfix for an error deployed this morning.
* Content
=> Add BASE_URL constant for search service

_agencies/cdc.md, _agencies/dhs.md, _agencies/fcc.md, _agencies/fda.md, _agencies/fema.md, _agencies/ftc.md, _agencies/irs.md, _agencies/sba.md, _agencies/treasury.md, _agencies/usda.md, _agencies/va.md, _includes/accordion.html, _includes/sources.html
Spelled out full agency names in the title attribute of the agency files, so the full name displays in the source info (footer) of each FAQ.
Please review the appearance on longer agency names that linebreak...and questions with multiple sources (see example links below). Do we want to consider the agency source being on a new line? Anything else we should consider/unanticipated impacts @danielnaab ?
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/spell-out-agency …
=> WIP: Spell out all agency names (titles) in agency files

api/v1/questions.json, api/v2/questions.json
Follow-on PR to #940 - add categories to API endpoints.
[api v1](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/questions-v2-categories/api/v1/questions.json)
[api v2](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/questions-v2-categories/api/v2/questions.json)
* Content
:sunglasses: [PREVIEW URL](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/questions-v2-categories/)
=> Update questions API to use new categories

_categories/protect-yourself.md, _data/homepage_promotion.yml
Updated entries in blue and gray boxes to go to category pages and not to specific questions.
Blue box
- How does it spread? 
Protect self gray box
- If I recovered from COVID-19, will I be immune? 
- Does CDC recommend the use of facemasks? 
Feel sick gray box
- What are the symptoms of COVID-19? 
- Should I get tested? and re-labeled to Do I need to get tested?
- What should I do if someone in my house gets sick with COVID-19? and re-labeled to If someone in my house gets sick with  COVID-19, what should I do?
* Content …
=> Update top boxes to go to categories

_config.yml, _includes/accordion.html, _includes/question-content.html, _includes/title.html, _layouts/agency.html, _layouts/post.html, styles/_posts.scss
Implements #983
* Remove accordion from single questions page
* Breadcrumb styling
* Update site title
* Add categories after single page question answer
Here's question with a long title that demos the breadcrumb styling: https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/single-question-page-tweaks/calls-to-small-businesses-promising-quick-financial-relief/
Here's a question with two categories that demos multi-cat styling: https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/single-question-page-tweaks/should-i-trust-ads-for-products-to-prevent-treat-cure-covid-19/
* Content
* *Content admin* or …
=> Single question page tweaks

_includes/alert-banner.html, _includes/questions-box.html, styles/_home.scss
Clean up WAVE accessibility checker alerts on missing header levels; implements #996 
* Content
=> Adjust header levels

.circleci/config.yml, package-lock.json
* Content
Issue: *The docker container upgraded node from v12 to v14 between builds causing the cached node_modules to be incompatible with v14.*
=> Invalidate CircleCI node_modules cache.
